const express = require('express')
const router = express.Router()
const fiturRoute = require('./fitur/fitur.route')
const organizationRoute = require('./organization/organization.route')
const projectRoute = require('./project/project.route')
const projectFiturRoute = require('./projectFitur/projectFitur.route')
const reportRoute = require('./report/report.route')
const rolesRoute = require('./roles/roles.route')
const tipeRoute = require('./tipe/tipe.route')
const userRoute = require('./user/user.route')
const voteRoute = require('./vote/vote.route')

router.use('/fitur', fiturRoute)
router.use('/organization', organizationRoute)
router.use('/project', projectRoute)
router.use('/projectFitur', projectFiturRoute)
router.use('/report', reportRoute)
router.use('/roles', rolesRoute)
router.use('/tipe', tipeRoute)
router.use('/user', userRoute)
router.use('/vote', voteRoute)

module.exports = router